### ISSUE TITLE
Use keyword arguments rather than positional arguments.

### ISSUE THREAD

**Issue by stevenharman** [pokonski/gush#10]
One thing that might make this library a bit easier to use would be keyword arguments to configure a Workflow, rather than positional arguments.  A quick look at the code suggests this is already doable (as the arguments are being collected by `*` and splatted back out when passing them along. So maybe just a tweak or mention in the README?

Thoughts?

**Comment by pokonski** [comment]
Yeah, I have no prefeference on that, since jobs have params which are a Hash. So Maybe a regular hash for both?

**Comment by stevenharman** [comment]
> Though keyword arguments in Ruby are, to be honest, a bit crappy and uncomfortable to use.

Oh? I've found them **super** nice since Ruby 2.1 where we have required and optional keyword args.

At any rate... I think (but have not verified) that they'll _Just Work :tm:_ as is.

**Comment by pokonski** [comment]
Oh, maybe I have an outdated bad impression from Ruby 2.0 :+1: Will check them out.

**Comment by dmitrypol** [comment]
+1
